apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: {{ .Values.type }}
    major: {{ .Values.version }}
  instances: {{ .Values.instances }}
  postgresUID: {{ if eq .Values.type "timescaledb" }}1000{{ else }}26{{ end }}
  postgresGID: {{ if eq .Values.type "timescaledb" }}1000{{ else }}26{{ end }}
  bootstrap:
    {{- if .Values.recovery.enabled }}
    recovery:
      source: origin
    {{- else }}
    initdb:
      database: {{ .Values.initdb.database | default .Release.Name }}
      owner: {{ .Values.initdb.owner }}
      secret:
        name: {{ .Values.initdb.secret.name }}
      {{- if .Values.initdb.postInitSQL }}
      postInitSQL:
        {{- .Values.initdb.postInitSQL | toYaml | nindent 6 }}
      {{- end }}
      
      {{- $sql := .Values.initdb.postInitApplicationSQL | default list }}

      {{- if eq .Values.type "timescaledb" }}
      {{- $sql = append $sql "CREATE EXTENSION IF NOT EXISTS timescaledb;" }}
      {{- end }}

      {{- if $sql }}
      postInitApplicationSQL:
      {{ toYaml $sql | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- if .Values.enableSuperuserAccess }}
  enableSuperuserAccess: true 
  superuserSecret:
    name: {{ .Values.superuserSecret.name }}
  {{- end }}

  storage:
    storageClass: {{ .Values.storageClass }}
    size: {{ .Values.storage.size }}

  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.backup.enabled }}
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: {{ .Release.Name }}-backup
  {{- end }}

  affinity:
    enablePodAntiAffinity: {{ .Values.affinity.enablePodAntiAffinity }}
    topologyKey: {{ .Values.affinity.topologyKey }}

  {{- if eq .Values.type "timescaledb" }}
  postgresql:
    shared_preload_libraries:
      - timescaledb
  {{- end }}
  
  {{ if .Values.recovery.enabled }}
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: {{ .Release.Name }}-recovery
          serverName: {{ .Values.recovery.serverName }}
  {{- end }}
