apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: {{ .Values.type }}
    major: {{ .Values.version }}
  instances: {{ .Values.instances }}
  postgresUID: {{ if eq .Values.type "timescaledb" }}1000{{ else }}26{{ end }}
  postgresGID: {{ if eq .Values.type "timescaledb" }}1000{{ else }}26{{ end }}
  bootstrap:
    initdb:
      database: {{ .Values.initdb.database | default .Release.Name }}
      owner: {{ .Values.initdb.owner }}
      secret:
        name: {{ .Values.initdb.secret.name }}
      {{- if .Values.initdb.postInitSQL }}
      postInitSQL:
        {{- .Values.initdb.postInitSQL | toYaml | nindent 6 }}
      {{- end }}
      
      {{- $sql := .Values.initdb.postInitApplicationSQL | default list }}

      {{- if eq .Values.type "timescaledb" }}
      {{- $sql = append $sql "CREATE EXTENSION IF NOT EXISTS timescaledb;" }}
      {{- end }}

      {{- if $sql }}
      postInitApplicationSQL:
      {{ toYaml $sql | nindent 8 }}
      {{- end }}

  {{- if .Values.enableSuperuserAccess }}
  enableSuperuserAccess: true 
  superuserSecret:
    name: {{ .Values.superuserSecret.name }}
  {{- end }}

  storage:
    storageClass: {{ .Values.storageClass }}
    size: {{ .Values.storage.size }}

  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.backup.enabled }}
  {{- $bucketName := "" }}
  {{- $bucketHost := "" }}
  {{- $secretName := .Values.backup.secret.name | default .Values.backup.obc.name }}

  {{- if .Values.backup.obc.name }}
    {{- $bucketConfig := (lookup "v1" "ConfigMap" .Release.Namespace .Values.backup.obc.name) }}
    {{- if $bucketConfig.data }}
      {{- $bucketName = printf "s3://%s/" (get $bucketConfig.data "BUCKET_NAME") }}
      {{- $bucketHost = printf "http://%s:%s" (get $bucketConfig.data "BUCKET_HOST") (get $bucketConfig.data "BUCKET_PORT") }}
    {{- end }}
  {{- else }}
    {{- $bucketName = .Values.backup.destinationPath }}
    {{- $bucketHost = .Values.backup.endpointURL }}
  {{- end }}

  {{- if and $bucketName $bucketHost }}
  backup:
    barmanObjectStore:
      destinationPath: {{ $bucketName }}
      endpointURL: {{ $bucketHost }}
      s3Credentials:
        accessKeyId:
          name: {{ $secretName }}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: {{ $secretName }}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2
    retentionPolicy: {{ .Values.backup.retentionPolicy }}
  {{- end }}
  {{- end }}

  affinity:
    enablePodAntiAffinity: {{ .Values.affinity.enablePodAntiAffinity }}
    topologyKey: {{ .Values.affinity.topologyKey }}

  {{- if eq .Values.type "timescaledb" }}
  postgresql:
    shared_preload_libraries:
      - timescaledb
  {{- end }}

  monitoring:
    enablePodMonitor: {{ .Values.monitoring.enablePodMonitor }}