{{- if eq .Values.type "timescaledb" }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: timescaledb
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  images:
    - major: 16
      image: timescale/timescaledb-ha:pg16.14-ts2.27.1
    - major: 18
      image: timescale/timescaledb-ha:pg18.4-ts2.27.1
{{ end }}