{{- if eq .Values.type "postgresql" }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  images:
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.14
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.10
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.4
{{ end }}