{{- if .Values.backup.enabled }}
{{- $secretName := .Values.backup.secret.name | default .Values.backup.obc.name }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Release.Name }}-backup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,pre-rollback
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  retentionPolicy: {{ .Values.backup.retentionPolicy}}
  configuration:
    destinationPath: s3://{{ .Values.backup.obc.name }}
    endpointURL: {{ .Values.backup.obc.endpoint }}
    s3Credentials:
      accessKeyId:
        name: {{ $secretName }}
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: {{ $secretName }}
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
    data:
      compression: gzip
      jobs: 2
{{- end }}
