# Default values for cnpg-cluster.
type: postgresql
version: 17

instances: 2

initdb:
  database: "" # defaults to release name
  owner: app
  secret:
    name: cnpg-app-user
  postInitSQL: []
  # Runs in default "postgres" database after cluster initialization
  # Example of postInitSQL:
  # postInitSQL:
  #   - "CREATE ROLE app WITH LOGIN PASSWORD 'password';"
  postInitApplicationSQL: []
  # Runs in app database only (database specified in initdb.database) after postInitSQL
  # Example of postInitApplicationSQL:
  # postInitApplicationSQL:
  #   - "CREATE TABLE IF NOT EXISTS demo (id INT PRIMARY KEY);"

enableSuperuserAccess: false
superuserSecret:
  name: cnpg-superuser

storageClass: local-path
storage:
  size: 5Gi

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

backup:
  enabled: false
  obc:
    name: ""
    storageClassName: rook-ceph-bucket
  destinationPath: ""
  endpointURL: ""
  secret:
    name: ""
  schedule: "0 0 0 * * *" # daily at midnight
  retentionPolicy: "30d"

affinity:
  enablePodAntiAffinity: true
  topologyKey: kubernetes.io/hostname

monitoring:
  enablePodMonitor: true
