{{- if or .Values.networkPolicy.ingress .Values.networkPolicy.egress }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  endpointSelector:
    {{- if .Values.networkPolicy.endpointSelector }}
    matchLabels:
      {{- range $key, $value := .Values.networkPolicy.endpointSelector }}
      {{ $key }}: {{ $value }}
      {{- end }}
    {{- else }}
    matchLabels: {}
    {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
