---
apiVersion: source.toolkit.fluxcd.io/v1
kind: {{ .Values.repository.kind }}
metadata:
  name: {{ .Values.namespace }}-repo
  namespace: {{ .Values.namespace }}
spec:
  interval: {{ .Values.repository.interval }}
  url: {{ .Values.repository.url }}
  ref:
    branch: {{ .Values.repository.branch }}
  {{- if .Values.repository.secretRef.name }}
  secretRef:
    name: {{ .Values.repository.secretRef.name }}
  {{- end }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  interval: {{ .Values.repository.interval }}
  sourceRef:
    kind: {{ .Values.repository.kind }}
    name: {{ .Values.namespace }}-repo
  path: {{ .Values.repository.path }}
  prune: true
  targetNamespace: {{ .Values.namespace }}
  serviceAccountName: {{ .Values.namespace }}
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
